"""program_synthesis_agent.py — self-contained ARC-AGI-3 agent.

Generated by ARC_AGI_3_Kaggle.ipynb (Arena.ai Agent Mode build).
Implements hypothesis-driven program synthesis over ARC-AGI-3
interaction traces: perception -> hypothesis bank -> DSL-predicted
frame -> act -> validate -> confirm/refine.

No third-party dependencies beyond numpy (+ arcengine when present).
"""
import numpy as np

# ============================================================
# PROTOCOL LAYER — official arcengine API when available, else a
# byte-compatible shim (same names, values and semantics).
# ============================================================
import numpy as np

GRID = 64   # official ARC-AGI-3 screen size (ACTION6 x,y range 0..63)
CELL = 8    # demo games use an 8x8 logical lattice of 8x8-pixel blocks

try:
    from arcengine import FrameData as _RealFrameData  # noqa: F401
    from arcengine import GameAction, GameState
    from arcengine.enums import SimpleAction, ComplexAction, FrameData, FrameDataRaw, ActionInput
    ARCENGINE_AVAILABLE = True
except Exception:
    ARCENGINE_AVAILABLE = False

    from enum import Enum
    from typing import Any, List, Optional, Union

    MAX_REASONING_BYTES = 16 * 1024

    class GameState(str, Enum):
        NOT_PLAYED = "NOT_PLAYED"
        NOT_FINISHED = "NOT_FINISHED"
        WIN = "WIN"
        GAME_OVER = "GAME_OVER"

    class SimpleAction:
        def __init__(self, game_id: str = ""):
            self.game_id = game_id
        def model_dump(self):
            return {"game_id": self.game_id}

    class ComplexAction:
        def __init__(self, game_id: str = "", x: int = 0, y: int = 0):
            if not (0 <= x <= 63 and 0 <= y <= 63):
                raise ValueError("x and y must be within [0, 63]")
            self.game_id = game_id
            self.x = x
            self.y = y
        def model_dump(self):
            return {"game_id": self.game_id, "x": self.x, "y": self.y}

    class GameAction(Enum):
        RESET = (0, SimpleAction)
        ACTION1 = (1, SimpleAction)
        ACTION2 = (2, SimpleAction)
        ACTION3 = (3, SimpleAction)
        ACTION4 = (4, SimpleAction)
        ACTION5 = (5, SimpleAction)
        ACTION6 = (6, ComplexAction)
        ACTION7 = (7, SimpleAction)

        def __init__(self, action_id, action_type):
            self._value_ = action_id
            self._atype = action_type
            self.action_data = action_type()

        def is_simple(self):
            return self._atype is SimpleAction

        def is_complex(self):
            return self._atype is ComplexAction

        def set_data(self, data):
            self.action_data = self._atype(**data)
            return self.action_data

        @classmethod
        def from_id(cls, action_id):
            for a in cls:
                if a.value == action_id:
                    return a
            raise ValueError(f"No GameAction with id {action_id}")

    class ActionInput:
        def __init__(self, id=GameAction.RESET, data=None, reasoning=None):
            self.id = id
            self.data = data or {}
            self.reasoning = reasoning

    class FrameData:
        """Mirrors arcengine.FrameData (pydantic model) as a plain class."""
        def __init__(self, game_id="", frame=None, state=GameState.NOT_PLAYED,
                     levels_completed=0, win_levels=0, action_input=None,
                     guid=None, full_reset=False, available_actions=None):
            self.game_id = game_id
            self.frame = frame or []          # list of 2D int grids
            self.state = state
            self.levels_completed = levels_completed
            self.win_levels = win_levels
            self.action_input = action_input or ActionInput()
            self.guid = guid
            self.full_reset = full_reset
            self.available_actions = list(available_actions or [])

        def is_empty(self):
            return len(self.frame) == 0


def frame_grids(frame_data) -> list:
    """FrameData.frame -> list of np.ndarray grids (handles both list and ndarray inputs)."""
    grids = []
    for layer in (frame_data.frame or []):
        arr = np.asarray(layer)
        if arr.ndim == 2:
            grids.append(arr)
    return grids


def merged_view(frame_data):
    """All layers overlaid: later layers win where nonzero."""
    grids = frame_grids(frame_data)
    if not grids:
        return np.zeros((64, 64), dtype=int)
    base = np.zeros_like(grids[0])
    for g in grids:
        base = np.where(g != 0, g, base)
    return base


# ============================================================
# PERCEPTION MODULE (from the 4CBON2 L4 design, adapted to
# ARC-AGI-3 screen frames: a list of 2D integer grids)
# ============================================================
from collections import deque


def find_objects(grid):
    """Connected components of same-coloured, non-background pixels.
    Returns objects as dicts: id, color, pixels(frozenset), bbox, size, centroid."""
    objects = []
    visited = set()
    obj_id = 0
    h, w = grid.shape
    for r in range(h):
        for c in range(w):
            if grid[r, c] == 0 or (r, c) in visited:
                continue
            color = int(grid[r, c])
            obj_id += 1
            q = deque([(r, c)])
            visited.add((r, c))
            pixels = []
            min_r, max_r, min_c, max_c = r, r, c, c
            while q:
                cr, cc = q.popleft()
                pixels.append((cr, cc))
                min_r, max_r = min(min_r, cr), max(max_r, cr)
                min_c, max_c = min(min_c, cc), max(max_c, cc)
                for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                    nr, nc = cr + dr, cc + dc
                    if (0 <= nr < h and 0 <= nc < w and (nr, nc) not in visited
                            and grid[nr, nc] == color):
                        visited.add((nr, nc))
                        q.append((nr, nc))
            cy = sum(p[0] for p in pixels) / len(pixels)
            cx = sum(p[1] for p in pixels) / len(pixels)
            objects.append({
                "id": obj_id, "color": color,
                "pixels": frozenset(pixels),
                "bbox": (min_r, min_c, max_r, max_c),
                "size": len(pixels),
                "centroid": (cy, cx),
            })
    return objects


def color_stats(grid):
    values, counts = np.unique(grid, return_counts=True)
    return {int(v): int(n) for v, n in zip(values, counts) if v != 0}


def frame_diff(grid_a, grid_b):
    """Boolean mask of pixels that changed between two frames."""
    if grid_a.shape != grid_b.shape:
        return np.ones_like(grid_b, dtype=bool)
    return grid_a != grid_b


def changed_cells(diff_mask):
    return {(int(r), int(c)) for r, c in zip(*np.nonzero(diff_mask))}


def salience_rank(objects):
    """Order objects by how 'interesting' they are: rarer colour first,
    then smaller size. Returns list of (score_explanation, obj)."""
    color_count = {}
    for o in objects:
        color_count[o["color"]] = color_count.get(o["color"], 0) + 1
    ranked = sorted(objects,
                    key=lambda o: (color_count[o["color"]], o["size"], o["bbox"]),
                    reverse=False)
    return ranked, color_count


def objects_in_cell(obj, cell_r, cell_c):
    """True if the object's centroid falls inside logical cell (cell_r, cell_c)."""
    cy, cx = obj["centroid"]
    return (cell_r * CELL) <= cy < (cell_r + 1) * CELL and (cell_c * CELL) <= cx < (cell_c + 1) * CELL


def describe_action_effect(before, after, action_id, data):
    """Human-readable trace of what an action did — the agent's feedback signal."""
    d = frame_diff(before, after)
    n = int(d.sum())
    if n == 0:
        return {"action": action_id, "data": data, "changed_pixels": 0, "note": "no visible change"}
    rows = np.nonzero(d)[0]
    cols = np.nonzero(d)[1]
    return {"action": action_id, "data": data, "changed_pixels": n,
            "region": (int(rows.min()), int(cols.min()), int(rows.max()), int(cols.max())),
            "note": f"{n} pixels changed"}


# ============================================================
# PRIMITIVE OPERATION LIBRARY (DSL) — carried over verbatim in
# spirit from the 4CBON2 L4 design. Grid transformations used to
# express and validate hypothesised world dynamics.
# ============================================================
import copy


def prim_identity(grid):
    return copy.deepcopy(grid)


def prim_global_recolor(grid, old_color, new_color):
    g = copy.deepcopy(grid)
    g[g == old_color] = new_color
    return g


def prim_recolor_region(grid, mask, new_color):
    g = copy.deepcopy(grid)
    g[mask] = new_color
    return g


def prim_fill_region(grid, x, y, target_color):
    g = copy.deepcopy(grid)
    if not (0 <= y < g.shape[0] and 0 <= x < g.shape[1]):
        return g
    original = g[y, x]
    if original == target_color:
        return g
    q = deque([(y, x)])
    seen = {(y, x)}
    g[y, x] = target_color
    while q:
        r, c = q.popleft()
        for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            nr, nc = r + dr, c + dc
            if (0 <= nr < g.shape[0] and 0 <= nc < g.shape[1]
                    and g[nr, nc] == original and (nr, nc) not in seen):
                g[nr, nc] = target_color
                seen.add((nr, nc))
                q.append((nr, nc))
    return g


def prim_move_region(grid, mask, dr, dc):
    g = copy.deepcopy(grid)
    color = g[mask][0] if mask.any() else 0
    g[mask] = 0
    rows = np.nonzero(mask)[0] + dr
    cols = np.nonzero(mask)[1] + dc
    keep = (rows >= 0) & (rows < g.shape[0]) & (cols >= 0) & (cols < g.shape[1])
    g[rows[keep], cols[keep]] = color
    return g


def prim_rotate(grid, k):
    return np.rot90(grid, k)


def prim_flip(grid, axis):
    return np.flip(grid, axis)


PRIMITIVES = {
    "identity": prim_identity,
    "global_recolor": prim_global_recolor,
    "recolor_region": prim_recolor_region,
    "fill_region": prim_fill_region,
    "move_region": prim_move_region,
    "rotate": prim_rotate,
    "flip": prim_flip,
}


# >>> BEGIN SYNTHESIS CORE (this block is embedded verbatim in the
# submission file by the packaging cell — keep it framework-free)
CLICK_SELECTORS = ["rarest_color", "smallest_object",
                   "corner_sample_color", "largest_object"]


class ProgramSynthesisCore:
    """All decision logic, independent of any agent framework."""

    GAME_MEMORY = {}   # game_id -> {"selector": str, "kind": "click"|"move"}

    def __init__(self, verbose=False):
        self.verbose = verbose
        self.reset_all()

    def reset_all(self):
        self.game_id = ""
        self.history = []
        self.pending = None        # (kind, action_id, predicted_grid, note)
        self.level = 0
        self.mode = None
        # click-game state
        self.sel_order = list(CLICK_SELECTORS)
        self.queue = []
        self.queue_ptr = 0
        self.clicked_sig = set()
        self.confirmed = None
        # move-game state
        self.dirs = {}             # action_id -> (dr, dc) in cells
        self.probe_attempts = {}   # action_id -> blocked-probe count
        self.player_color = None
        self.stuck = 0
        self._alt = 0

    # ------------------------------------------------------------------ API
    def new_episode(self, game_id):
        gmem = ProgramSynthesisCore.GAME_MEMORY.get(game_id)
        self.reset_all()
        self.game_id = game_id
        if gmem:
            # keep cross-episode knowledge; confirmed selector goes first
            s = gmem.get("selector")
            if gmem.get("kind") == "click" and s in CLICK_SELECTORS:
                self.sel_order = [s] + [x for x in CLICK_SELECTORS if x != s]
                self.confirmed = s
            elif gmem.get("kind") == "move":
                self.dirs = dict(gmem.get("dirs") or {})
                self.player_color = gmem.get("player_color")

    def next_action(self, frame):
        """Returns (action_id, data, reasoning). Sees each frame exactly once."""
        grid = merged_view(frame) if frame.frame else None
        if grid is None:
            return 0, {"game_id": self.game_id}, {"note": "no frame yet"}
        if self.history:
            self._process_feedback(self.history[-1], grid, frame)
        self.history.append(grid)

        if frame.state in (GameState.NOT_PLAYED, GameState.GAME_OVER):
            self._clear_level_state()
            return 0, {"game_id": self.game_id}, {
                "strategy": "reset", "why": "restart level with current hypothesis",
                "hypothesis": self.sel_order[0]}

        avail = list(frame.available_actions or [])
        if not avail:
            return 0, {"game_id": self.game_id}, {"note": "no available actions"}
        self.mode = "click" if 6 in avail else "move"
        if self.mode == "click":
            return self._click_policy(grid, frame)
        return self._move_policy(grid, frame)

    # ------------------------------------------------------------ feedback
    def _process_feedback(self, prev, cur, frame):
        """Validate the previous action's prediction against reality."""
        kind, aid, predicted, note = (self.pending or (None, None, None, None))
        self.pending = None
        advanced = frame.levels_completed > self.level
        if frame.state == GameState.WIN:
            advanced = True
        if advanced:
            self.level = frame.levels_completed
            self._confirm(note="level advanced")
            self._clear_level_state()
            return
        if kind == "click":
            changed = frame_diff(prev, cur).any()
            if not changed:
                if note:
                    self.clicked_sig.add(note)       # blacklist this object
                return
            if predicted is not None:
                ok = float((predicted == cur).mean())
                if ok >= 0.97:
                    self._confirm(note="frame prediction validated (IoU~1)")
                else:
                    self._demote(why="prediction mismatch", score=ok)
        elif kind == "probe" and aid is not None:
            self._learn_direction(prev, cur, aid)
        elif kind == "move":
            self._learn_direction(prev, cur, aid, quiet=True)
            moved = frame_diff(prev, cur).any()
            self.stuck = 0 if moved else self.stuck + 1

    # ---------------------------------------------------------- click games
    def _select_targets(self, sel, objs):
        if sel == "rarest_color":
            counts = {}
            for o in objs:
                counts[o["color"]] = counts.get(o["color"], 0) + o["size"]
            if not counts:
                return []
            rare = min(counts, key=lambda c: (counts[c], c))
            return [o for o in objs if o["color"] == rare]
        if sel == "smallest_object":
            return [min(objs, key=lambda o: (o["size"], o["bbox"]))]
        if sel == "corner_sample_color":
            corner = [o for o in objs if o["bbox"][0] < CELL and o["bbox"][1] < CELL]
            if not corner:
                return []
            sample = corner[0]
            return [o for o in objs
                    if o["color"] == sample["color"] and o["id"] != sample["id"]]
        if sel == "largest_object":
            return [max(objs, key=lambda o: o["size"])]
        return []

    def _click_policy(self, grid, frame, _depth=0):
        objs = find_objects(grid)
        if not objs:
            aid = (frame.available_actions or [1])[0]
            return aid, {"game_id": self.game_id}, {"note": "no objects; idle action"}
        sel = self.sel_order[0]
        if not self.queue:
            targets = self._select_targets(sel, objs)
            # salience order inside the selector: rarest colour, then smallest
            counts = {}
            for o in objs:
                counts[o["color"]] = counts.get(o["color"], 0) + 1
            targets = sorted(
                targets,
                key=lambda o: (counts[o["color"]], o["size"], o["bbox"]))
            self.queue = targets
            self.queue_ptr = 0
        target = None
        while self.queue_ptr < len(self.queue):
            cand = self.queue[self.queue_ptr]
            cy, cx = cand["centroid"]
            cell = (int(cy) // CELL, int(cx) // CELL)
            if (cand["color"], cell) not in self.clicked_sig:
                target = cand
                break
            self.queue_ptr += 1
        if target is None:                       # selector exhausted -> refine
            if _depth >= len(CLICK_SELECTORS):   # every hypothesis failed
                ranked, _ = salience_rank(objs)
                o = ranked[0]
                cy, cx = o["centroid"]
                self.pending = ("click", 6, None, None)
                return 6, {"x": min(max(int(cx), 0), 63),
                           "y": min(max(int(cy), 0), 63),
                           "game_id": self.game_id}, {
                    "strategy": "fallback", "note": "hypothesis bank exhausted"}
            self._demote(why="all candidates clicked, no progress")
            return self._click_policy(grid, frame, _depth + 1)
        mask = np.zeros_like(grid, dtype=bool)
        for (r, c) in target["pixels"]:
            mask[r, c] = True
        predicted = prim_recolor_region(grid, mask, 0)   # DSL: object vanishes
        cy, cx = target["centroid"]
        x, y = min(max(int(round(cx)), 0), 63), min(max(int(round(cy)), 0), 63)
        sig = (target["color"], (int(cy) // CELL, int(cx) // CELL))
        self.pending = ("click", 6, predicted, sig)
        self.queue_ptr += 1
        reasoning = {
            "strategy": "program synthesis", "hypothesis": sel,
            "program": f"click({sel})",
            "prediction": "target object's pixels become background",
            "confirmed": self.confirmed == sel,
            "evidence": f"queue position {self.queue_ptr}/{len(self.queue)}",
        }
        if self.verbose:
            print(f"    [synth] hyp={sel} click color={target['color']} "
                  f"size={target['size']} @({y},{x})")
        return 6, {"x": x, "y": y, "game_id": self.game_id}, reasoning

    # ---------------------------------------------------------- move games
    def _learn_direction(self, prev, cur, aid, quiet=False):
        if aid is None or aid in self.dirs:
            return
        hole = (prev != 0) & (cur == 0)
        fill = (prev == 0) & (cur != 0)
        if hole.any() and fill.any():
            hr, hc = np.nonzero(hole)
            fr, fc = np.nonzero(fill)
            dr = int(round(fr.mean() - hr.mean()))
            dc = int(round(fc.mean() - hc.mean()))
            self.dirs[aid] = (int(np.sign(dr)) if abs(dr) > 1 else 0,
                              int(np.sign(dc)) if abs(dc) > 1 else 0)
            self.player_color = int(np.bincount(prev[hole]).argmax())
            if not quiet and self.verbose:
                print(f"    [synth] probe ACTION{aid}: delta=({dr},{dc})px "
                      f"-> cell dir {self.dirs[aid]}")
        else:
            # blocked (wall/edge): remember the attempt, re-probe later
            self.probe_attempts[aid] = self.probe_attempts.get(aid, 0) + 1
            if self.probe_attempts[aid] >= 3:
                self.dirs[aid] = (0, 0)   # give up: assume ineffective
            if not quiet and self.verbose:
                print(f"    [synth] probe ACTION{aid}: blocked "
                      f"(attempt {self.probe_attempts[aid]})")

    def _move_policy(self, grid, frame):
        avail = [a for a in frame.available_actions if a != 0]
        unprobed = [a for a in avail
                    if a not in self.dirs
                    and self.probe_attempts.get(a, 0) < 3]
        if unprobed:                                   # exploration probes
            aid = unprobed[0]
            self.pending = ("probe", aid, None, None)
            return aid, {"game_id": self.game_id}, {
                "strategy": "program synthesis", "phase": "probe controls",
                "program": "for each ACTION: observe object displacement"}
        objs = find_objects(grid)
        if not objs or self.player_color is None:
            aid = avail[0]
            return aid, {"game_id": self.game_id}, {"note": "no moving object found"}
        players = [o for o in objs if o["color"] == self.player_color]
        if not players:
            aid = avail[0]
            return aid, {"game_id": self.game_id}, {"note": "player lost"}
        player = players[0]
        # goal = most salient non-player object
        others = [o for o in objs if o["color"] != self.player_color]
        if not others:
            aid = avail[0]
            return aid, {"game_id": self.game_id}, {"note": "no goal visible"}
        goal = salience_rank(others)[0][0]
        py, px = player["centroid"]
        gy, gx = goal["centroid"]

        def dist_after(aid_):
            dr, dc = self.dirs.get(aid_, (0, 0))
            return abs(py + dr * CELL - gy) + abs(px + dc * CELL - gx)

        ordered = sorted(avail, key=dist_after)
        if self.stuck >= 2:                 # anti-deadlock jitter
            ordered = ordered[1:] + ordered[:1]
            self.stuck = 0
        aid = ordered[0]
        dr, dc = self.dirs.get(aid, (0, 0))
        mask = np.zeros_like(grid, dtype=bool)
        for (r, c) in player["pixels"]:
            mask[r, c] = True
        predicted = prim_move_region(grid, mask, dr * CELL, dc * CELL)
        self.pending = ("move", aid, predicted, None)
        return aid, {"game_id": self.game_id}, {
            "strategy": "program synthesis",
            "program": "while not at goal: apply action minimising Manhattan distance",
            "controls": {str(k): v for k, v in self.dirs.items()},
            "player_color": self.player_color, "goal_color": goal["color"]}

    # ---------------------------------------------------------- hypothesis Mgmt
    def _confirm(self, note):
        if self.mode == "move":                 # movement program validated
            ProgramSynthesisCore.GAME_MEMORY[self.game_id] = {
                "kind": "move", "dirs": dict(self.dirs),
                "player_color": self.player_color}
            if self.verbose:
                print(f"    [synth] CONFIRMED control program "
                      f"{self.dirs} ({note})")
            return
        sel = self.sel_order[0]
        self.confirmed = sel
        ProgramSynthesisCore.GAME_MEMORY[self.game_id] = {
            "selector": sel, "kind": "click"}
        if self.verbose:
            print(f"    [synth] CONFIRMED hypothesis '{sel}' ({note})")

    def _demote(self, why, score=None):
        sel = self.sel_order.pop(0)
        self.sel_order.append(sel)
        self.queue, self.queue_ptr, self.clicked_sig = [], 0, set()
        self.confirmed = None
        if self.verbose:
            print(f"    [synth] demoted '{sel}' ({why}"
                  + (f", match={score:.2f})" if score is not None else ")"))

    def _clear_level_state(self):
        self.queue, self.queue_ptr, self.clicked_sig = [], 0, set()
        self.pending = None


# <<< END SYNTHESIS CORE


# ==========================================================================
# Adapter for the official ARC-AGI-3-Agents kit
# ==========================================================================
# Usage: clone https://github.com/arcprize/ARC-AGI-3-Agents, drop this file
# next to its agents/ package and register the agent, e.g. in
# agents/__init__.py:
#
#     from program_synthesis_agent import ProgramSynthesisKitAgent
#     AVAILABLE_AGENTS["program_synthesis"] = ProgramSynthesisKitAgent
#
# The agent implements the kit's ABC (is_done / choose_action) and attaches
# a JSON reasoning blob to every action, as the API allows.

try:
    from agents.agent import Agent as _KitAgent
except Exception:                       # usable without the kit too
    _KitAgent = object


class ProgramSynthesisKitAgent(_KitAgent):
    """Hypothesis-driven program-synthesis agent for ARC-AGI-3.

    Decision loop per action: PERCEIVE objects in the frame -> pick/keep a
    hypothesis from the bank -> PREDICT the next frame with DSL primitives
    -> act -> VALIDATE the prediction against the real frame -> confirm or
    refine. Confirmed hypotheses persist per game across levels/episodes.
    """

    MAX_ACTIONS = 80

    def __init__(self, card_id="", game_id="", agent_name="program_synthesis",
                 ROOT_URL="", record=False, arc_env=None, tags=None):
        if _KitAgent is not object:
            super().__init__(card_id=card_id, game_id=game_id,
                             agent_name=agent_name, ROOT_URL=ROOT_URL,
                             record=record, arc_env=arc_env, tags=tags)
        else:
            self.game_id = game_id
            self.action_counter = 0
        self.core = ProgramSynthesisCore()
        self.core.new_episode(game_id)

    def is_done(self, frames, latest_frame):
        return (latest_frame.state == GameState.WIN
                or self.action_counter >= self.MAX_ACTIONS)

    def choose_action(self, frames, latest_frame):
        frame = frames[-1] if frames else latest_frame
        aid, data, reasoning = self.core.next_action(frame)
        action = GameAction.from_id(aid)
        if data:
            action.set_data(dict(data))
        action.reasoning = reasoning
        return action
